        var name = "Ajin";                   
        var age = 25;                        
        var salary = 45000.75;                
        var isEmployed = true;                
        var technologies = ["HTML", "CSS", "Bootstrap", "JavaScript"];
        var project = { name: "Flipkart Clone",status: "In Progress" };
        var experience = 3;                  
        var location = "Chennai";            
        var hasPortfolio = true;
        var totalIncome = salary * 12;      
        var taxRate = 0.18;                   
        var taxAmount = totalIncome * taxRate;
        var netIncome = totalIncome - taxAmount;
        var message = "Welcome to Web Development!";
        var courseModulesCompleted = 3;      
        var targetSalary = 60000;            
        var jobSearchActive = true;          
        var resumeKeywords = ["Front-End", "Full Stack", "React"]; 
        var nextGoal = "Master JavaScript ES6+";

        console.log("1. Name:", name);
        console.log("2. Age:", age);
        console.log("3. Monthly Salary:", salary);
        console.log("4. Employed:", isEmployed);
        console.log("5. Skills:", skills);
        console.log("6. Technologies:", technologies);
        console.log("7. Current Project:", project);
        console.log("8. Experience (years):", experience);
        console.log("9. Location:", location);
        console.log("10. Has Portfolio:", hasPortfolio);
        console.log("11. Annual Income:", totalIncome);
        console.log("12. Tax Rate:", taxRate);
        console.log("13. Tax Amount:", taxAmount);
        console.log("14. Net Annual Income:", netIncome);
        console.log("15. Greeting:", message);
        console.log("16. Modules Completed:", courseModulesCompleted);
        console.log("17. Target Salary:", targetSalary);
        console.log("18. Job Search Active:", jobSearchActive);
        console.log("19. Resume Keywords:", resumeKeywords);
        console.log("20. Next Goal:", nextGoal);